---
services:
  api:
    build: .
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}

  postgres:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  product-api:
    image: ghcr.io/paulopatto/fake-product-api:latest
    env_file:
      - .env
    environment:
      PORT: 8001
    ports:
      - "8001:8001"

volumes:
  postgres_data:
